### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by ericwgreene** [pcvera/dojo-complete#2]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.

```
Atom.Object.defineProperty.get (C:\Users\Eric\AppData\Local\atom\app-0.196.0\resources\app.asar\src\atom.js:57:13)
Object.activate (C:\Users\Eric\.atom\packages\dojo-complete\lib\dojo-complete.js:340:9)
Package.activateNow (C:\Users\Eric\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:222:19)
<unknown> (C:\Users\Eric\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:203:30)
```

**Comment by pcvera** [comment]
Removed calls to atom.workspaceView in v0.4.0
